# This makefile applies options. Set the options in the top-level makefile.

# Configure MCU to output ACLK to a pin
# 		On edb board must "unplug" op amp buffers by disconnecting JP1
ifeq ($(CONFIG_ROUTE_ACLK_TO_PIN),1)
CFLAGS += -DCONFIG_ROUTE_ACLK_TO_PIN
endif

# Clock testing mode: enter a blinker loop after configuring clocks
ifeq ($(CONFIG_CLOCK_TEST_MODE),1)
CFLAGS += -DCONFIG_CLOCK_TEST_MODE
endif

ifeq ($(CONFIG_MAIN_LOOP_LED),1)
CFLAGS += -DCONFIG_MAIN_LOOP_LED
endif

#override CFLAGS += $(LOCAL_CFLAGS)
